openshift/operator-framework-operator-controller

openshift/generate-manifests.sh, openshift/manifests/11-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
=> UPSTREAM: <carry>: use image placeholders

openshift/generate-manifests.sh, openshift/manifests/00-namespace-openshift-operator-controller.yml
=> UPSTREAM: <carry>: add namespace management annotation

openshift/dev_notes.md
To make the downstream repos self explanatory we need to link to the information about how the downstreaming process works.
=> OPRUN-3268: Add pointer to tooling README for downstreaming info

openshift/generate-manifests.sh, openshift/manifests/17-validatingadmissionpolicy-openshift-operator-controller-operator-controller-clusterextensions-package-uniqueness.yml, openshift/manifests/18-validatingadmissionpolicybinding-openshift-operator-controller-operator-controller-clusterextensions-package-uniqueness-binding.yml
* This reverts commit 3f079c45a30844eed5d31ff8e768cef8ebddd813.
* Adds new manifests with Validating Admission Policy APIs
=> OPRUN-3291: UPSTREAM: <carry>: Enable Validating Admission Policy APIs downstream

openshift/generate-manifests.sh, openshift/manifests/16-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
This PR explicitly sets the required SCC to be used to admit pods of the `operator-controller-controller-manager` deployment. The SCC chosen is the one that the pods are already getting admitted with, which means that this brings no change to the SCC used.
In some cases, custom SCCs can have higher priority than default SCCs, which means that they will be chosen over the default ones. This can lead to unexpected results; in order to protect openshift workloads from this, we must explicitly pin the required SCC to all our workloads in order to make sure that the expected one will be used.
- https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
=> AUTH-482: set required-scc for openshift workloads

openshift/generate-manifests.sh
The `default` directory was renamed `base`.
=> NO-ISSUE: UPSTREAM: <carry>: Update generate-manifests to handle new directory

openshift/generate-manifests.sh, openshift/manifests/11-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
[OCPBUGS-37549](https://issues.redhat.com/browse/OCPBUGS-37549)
Cherry-pick of #100 
**Description of the change:**
This PR explicitly sets the required SCC to be used to admit pods of the `operator-controller-controller-manager` deployment. The SCC chosen is the one that the pods are already getting admitted with, which means that this brings no change to the SCC used.
**Motivation for the change:**
In some cases, custom SCCs can have higher priority than default SCCs, which means that they will be chosen over the default ones. This can lead to unexpected results; in order to protect openshift workloads from this, we must explicitly pin the required SCC to all our workloads in order to make sure that the expected one will be used.
=> [release-4.15] OCPBUGS-37549: Set required-scc for openshift workloads

openshift/generate-manifests.sh, openshift/kustomize/overlays/openshift/kustomization.yaml, openshift/kustomize/overlays/openshift/patches/manager_deployment_mount_etc_containers.yaml, openshift/kustomize/overlays/openshift/patches/manager_namespace_privileged.yaml, openshift/kustomize/overlays/openshift/patches/manager_role.yaml, openshift/manifests/00-namespace-openshift-operator-controller.yml, openshift/manifests/09-clusterrole-operator-controller-manager-role.yml, openshift/manifests/18-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
In order for operator-controller to support disconnected clusters in OCP, it needs access to the `/etc/containers` directory on the node. This PR adds a hostPath volume mount to give it that access. It also changes the security configuration of the namespace and pod to allow privileged access (which is required for hostPath volume mounts).
=> OPRUN-3529: UPSTREAM: <carry>: manifests: add hostPath mount for /etc/containers

openshift/Makefile
Target is set to always pass while we work on getting the tests to pass downstream. Adding this target allows us to make e2e test changes without having to make PRs against the `openshift/release` repo each time.
=> OPRUN-3557: Add test-e2e target for downstream makefile

openshift/generate-manifests.sh, openshift/kustomize/overlays/openshift/kustomization.yaml, openshift/kustomize/overlays/openshift/patches/manager_deployment_mount_auth_host.yaml, openshift/manifests/18-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
MCO makes the global pull secrets available in `/var/lib/kubelet`. Operator-controller will look for these secrets in `/etc/operator-controller` folder, ref [operator-controller:1303](https://github.com/operator-framework/operator-controller/pull/1303).
This PR hostPath mounts the `/var/lib/kublet` directory from the host to the `/etc/operator-controller` directory in the container's filesystem.
RFC: [OLMv1 Private registry support](https://docs.google.com/document/d/1BXD6kj5zXHcGiqvJOikU2xs8kV26TPnzEKp6n7TKD4M/edit?usp=sharing)
=> OPRUN-3554:  UPSTREAM: <carry>: Add hostPath mount for `/var/lib/kubelet`

openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml, openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_node_selection.yaml, openshift/manifests/19-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Updates the nodeSelector and toleration on the operator-controller deployment via a kustomize patch to allow it to be scheduled on the master node.
=> OPRUN-3605: Update nodeSelector and tolerations on operator-controller deployment via kustomize patch

internal/catalogmetadata/cache/cache.go, internal/catalogmetadata/cache/cache_test.go, internal/controllers/clustercatalog_controller.go, internal/controllers/clustercatalog_controller_test.go, internal/controllers/clusterextension_controller.go
Temporary drop patch for https://github.com/operator-framework/operator-controller/pull/1489
=> OCPBUGS-44813: UPSTREAM: <drop>: catalog cache: retry cache population when cache contains an error

openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml, openshift/manifests/00-namespace-openshift-operator-controller.yml
It seems we need to set audit and warn levels to privileged to avoid tripping PSA PodSecurityViolation alerts.
=> OPRUN-3605: UPSTREAM: <carry>: namespace: use privileged PSA for audit and warn levels

openshift/Makefile, openshift/build-test-registry.sh, openshift/registry.Dockerfile
Removes the fake e2e `/bin/true` stub and enables the upstream e2e. Also adds an additional script to deploy the e2e bundle/catalog registry into the oc ci environment.
~~Requires:
https://github.com/openshift/release/pull/58887
https://github.com/openshift/operator-framework-operator-controller/pull/192
https://github.com/openshift/release/pull/58802~~
=> OPRUN-3587: Enable downstream e2e

internal/rukpak/convert/registryv1.go, internal/rukpak/convert/registryv1_test.go, internal/rukpak/convert/testdata/combine-properties-bundle/manifests/csv.yaml, internal/rukpak/convert/testdata/combine-properties-bundle/metadata/annotations.yaml, internal/rukpak/convert/testdata/combine-properties-bundle/metadata/properties.yaml
Manual cherry pick of [this commit](https://github.com/openshift/operator-framework-operator-controller/pull/199/commits/b9294a7b1839ec9dd02dcfc337e3a5fb7be30e78).
=> [release-4.18] OCPBUGS-45114: combine bundle properties from csv and metadata/properties.yaml

openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml, openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml, openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
This allows for use of the any image.config.openshift.io trusted CAs
=> OCPBUGS-48795: Add /etc/docker to the operator-controller and catalogd deployments

catalogd/cmd/catalogd/main.go, cmd/operator-controller/main.go
Extensive e2e tests revealed that our component might run into leader election timeouts during cluster bootstrap, causing sporadic alerts being generated.
This commit uses recommended settings for leaderelection:
```
LeaseDuration: 15s -> 137s
RenewDeadline: 10s -> 107s
RetryPeriod:    2s ->  26s
```
Warning: This will increase potential down-time of components to 163s in the worst case (up from 17s).
(LeaseDuration + RetryPeriod)
Source of recommended settings:
https://github.com/openshift/enhancements/blob/61581dcd985130357d6e4b0e72b87ee35394bf6e/CONVENTIONS.md#handling-kube-apiserver-disruption
=> OCPBUGS-48765: leaderelection settings

cmd/manager/main.go
This is a manual backport of https://github.com/openshift/operator-framework-operator-controller/pull/249 to fix leaderelection settings
=> OCPBUGS-49622: Fix leaderelection settings

catalogd/cmd/catalogd/main.go, catalogd/config/components/ca/patches/manager_deployment_cacerts.yaml, catalogd/internal/source/containers_image.go, cmd/operator-controller/main.go, config/components/tls/patches/manager_deployment_cert.yaml, internal/httputil/certpoolwatcher.go, internal/httputil/certpoolwatcher_test.go, internal/rukpak/source/containers_image.go, internal/rukpak/source/containers_image_test.go, internal/rukpak/source/util.go, internal/util/fs.go, openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml, openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
This is a consolidated downstreaming PR that incorporates the following changes:
- https://github.com/openshift/operator-framework-operator-controller/pull/254
- https://github.com/openshift/operator-framework-operator-controller/pull/253
- https://github.com/operator-framework/operator-controller/pull/1673
- https://github.com/operator-framework/operator-controller/pull/1672
=> OCPBUGS-49683: CA cert and catalog cache bug fixes

cmd/manager/main.go, config/components/tls/patches/manager_deployment_cert.yaml, internal/httputil/certpoolwatcher.go, internal/httputil/certpoolwatcher_test.go, openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Reverts openshift/operator-framework-operator-controller#256 due to failing singlenode jobs noted in
[TRT-1985](https://issues.redhat.com/browse/TRT-1985)
Testing with
`/payload-job periodic-ci-openshift-release-master-ci-4.19-e2e-aws-upgrade-ovn-single-node`
=> OCPBUGS-49759: Revert "[release-4.18] OCPBUGS-49715: CA cert and catalog cache bug fixes"

catalogd/cmd/catalogd/main.go, catalogd/config/components/ca/patches/manager_deployment_cacerts.yaml, cmd/operator-controller/main.go, config/components/tls/patches/manager_deployment_cert.yaml, internal/catalogmetadata/client/client.go, internal/httputil/certlog.go, internal/httputil/certpoolwatcher.go, internal/httputil/certpoolwatcher_test.go, internal/httputil/certutil.go, openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/catalogd/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml, openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
This adds:
* Logging of certs as they are loaded/watched
* Logging of certificate validations errors
* Removal of the use of subPath
* SSL_CERT_DIR and SSL_CERT_FILE support for certpoolwatcher
* separation and renaming of ca options in catalogd and operator-controller
=> OCPBUGS-49860: Fix certificate issues

cmd/manager/main.go, config/components/tls/patches/manager_deployment_cert.yaml, internal/catalogmetadata/client/client.go, internal/httputil/certlog.go, internal/httputil/certpoolwatcher.go, internal/httputil/certpoolwatcher_test.go, internal/httputil/certutil.go, openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml, openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Includes manifest updates, config updates, and logging.
=> OCPBUGS-49896: [release-4.18]: Certificate updates

openshift/Makefile
The `vet` target was removed upstream.
=> NO-ISSUE: Remove vet from openshift verify

openshift/Makefile
Skip a test that fails downstream due to /etc/containers volume mounting conflicts.
=> NO-ISSUE: Skip another upstream test

openshift/Makefile
Just call the same e2e tests in the same target that is defined in https://github.com/tmshort/openshift-release/blob/df9b9696af771cd0dc93ae17a290a92c4ef04d7d/ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main.yaml#L116C11-L123 to ensure that we are keeping the same previous behaviour of the legacy catalogd downstream repository.
=>  NO-ISSUE: Cleanup openshift/Makefile by removing no longer required comments regards catalogd e2e tests

cmd/manager/main.go, internal/rukpak/source/containers_image.go, test/e2e/cluster_extension_install_test.go, testdata/images/catalogs/test-catalog/v1/configs/catalog.yaml
Manual backport of [this commit](https://github.com/openshift/operator-framework-operator-controller/commit/f26bf236f3012a50efe89073a0d3dae26e75af86) with the catalogd parts removed and placed in [this PR](https://github.com/openshift/operator-framework-catalogd/pull/131).
=> [release-4.18] OCPBUGS-51141: Cache invalidate backport

openshift/Makefile, openshift/build-test-registry.sh, openshift/registry.Dockerfile
Enables upstream e2e for the release-4.18 branch.
=> [release-4.18] OCPBUGS-52246: Enable Upstream E2E for 4.18

internal/shared/util/http/certlog.go, internal/shared/util/http/certutil.go
Cherry-pick of upstream PR 1918
Some log levels were defaultLogLevel+1 (5), change those to defaultLogLevel (4)
Signed-off-by: Todd Short <tshort@redhat.com>
(cherry picked from commit 2f22dcf1da862e45f09edf4bdc309032ac03b556)
=> NO-ISSUE: Update certpoolwatcher log levels

openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
This forces us to _explicitly_ watch the `/var/ca-certs` dir, and properly reload the certs when the `x509.SystemCertPool()` may not.
=> OCPBUGS-54877: Add catalogd-cas-dir option to op-con

openshift/generate-manifests.sh, openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml, openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_annotations.yaml, openshift/manifests/00-namespace-openshift-operator-controller.yml
We are applying the changes from [PR #307](https://github.com/openshift/operator-framework-operator-controller/pull/307) to the operator-controller for the upcoming 4.18 release.
To enable the execution of make manifests under the openshift directory, I had to cherry-pick the fix introduced in [commit 79a11eaae689672e380bcd0c038a9a616d6cc110](https://github.com/openshift/operator-framework-operator-controller/commit/79a11eaae689672e380bcd0c038a9a616d6cc110), which updates the script accordingly.
Furthermore, due to the ongoing monorepo initiative, the changes required for catalogd must be applied manually in the corresponding repository: [openshift/operator-framework-catalogd](https://github.com/openshift/operator-framework-catalogd). See: …
=> OCPBUGS-48478: [release-4.18] - Add openshift node selector annotation (operator-controller ONLY)

openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml, openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml, openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml, openshift/catalogd/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml, openshift/catalogd/manifests/19-clustercatalog-openshift-certified-operators.yml, openshift/catalogd/manifests/20-clustercatalog-openshift-community-operators.yml, openshift/catalogd/manifests/21-clustercatalog-openshift-redhat-marketplace.yml, openshift/catalogd/manifests/22-clustercatalog-openshift-redhat-operators.yml
This reverts commit a98980b70ca781ee96379e3b999515fe8189d200.
=> OCPBUGS-56047: revert "Bump catalog versions to 4.19 [main]"

openshift/HOWTO-origin-tests.md
techpreview is no longer a required option.
=> NO-ISSUE: Update HOWTO-origin-tests

openshift/default-catalog-consistency/pkg/extract/extract.go
=> NO-ISSUE: [DefaultCatalogTests]: Allow to pass auth path for docker credentials

openshift/default-catalog-consistency/pkg/extract/extract.go
The change is required to allow the tests run in the OCP/ci. See that we are facing the error:
```
Will run [1m4[0m of [1m4[0m specs
Using registry auth file: /var/run/secrets/ci.openshift.io/cluster-profile/pull-secret
no default policy found for (registry.redhat.io/redhat/certified-operator-index:v4.18), using insecure policy
[38;5;243m------------------------------[0m
[38;5;9m• [FAILED] [3.087 seconds][0m
[0mCheck Catalog Consistency [38;5;9m[1m[It] validates image: certified-operator-index[0m
[38;5;243m/go/src/github.com/openshift/operator-framework-operator-controller/openshift/default-catalog-consistency/test/validate/suite_test.go:30[0m
[38;5;243mTimeline >>[0m
[1mSTEP:[0m Validating image: registry.redhat.io/redhat/certified-operator-index:v4.18 [38;5;243m@ …
```
=> NO-ISSUE: <carry>: fix: set NoLchown=true to allow image unpack on OCPci

openshift/default-catalog-consistency/pkg/extract/extract.go, openshift/default-catalog-consistency/test/validate/suite_test.go
Motivated by @joelanford  comments: https://github.com/openshift/operator-framework-operator-controller/pull/345#discussion_r2094101091
c/c @joelanford
=> NO-ISSUE: <carry>: [DefaultCatalogTests]: Moving parse of ENVVAR to the caller (follow-up 345)

openshift/default-catalog-consistency/pkg/extract/extract.go
This change is to allow us to integrate with the OCP periodic (https://github.com/openshift/release/pull/65050)
We have been facing issues:
```
Will run [1m4[0m of [1m4[0m specs
no default policy found for (registry.redhat.io/redhat/certified-operator-index:v4.18), using insecure policy
[38;5;243m------------------------------[0m
[38;5;9m• [FAILED] [7.154 seconds][0m
[0mCheck Catalog Consistency [38;5;9m[1m[It] validates image: certified-operator-index[0m
[38;5;243m/go/src/github.com/openshift/operator-framework-operator-controller/openshift/default-catalog-consistency/test/validate/suite_test.go:53[0m
[38;5;243mTimeline >>[0m
[1mSTEP:[0m Validating image: registry.redhat.io/redhat/certified-operator-index:v4.18 [38;5;243m@ 05/20/25 15:37:22.142[0m …
```
=> NO-ISSUE: [Default Catalog]: Create tmp dir to extract layers with right permissions to avoid issues scenarios

openshift/default-catalog-consistency/Makefile, openshift/default-catalog-consistency/README.md, openshift/default-catalog-consistency/pkg/check/check.go, openshift/default-catalog-consistency/pkg/check/image.go, openshift/default-catalog-consistency/pkg/extract/extract.go, openshift/default-catalog-consistency/test/utils/utils.go, openshift/default-catalog-consistency/test/validate/suite_test.go
To address some minor enhancements before we squash the commits and cherry-pick
- Add targets to validate the code in the Makefile
- Configure to use Bingo from the main project
- Fix lint issues
- Address comments: https://github.com/openshift/operator-framework-operator-controller/pull/355
=> NO-ISSUE: [Default Catalog Tests]: Final cleanups and enhancements of initial implementation

openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
Fix the `operator-controller` part, the same as #329
```go
jiazha-mac:~ jiazha$ oc exec operator-controller-controller-manager-78f674f5f8-ww74h -- ls -R /etc/docker 
ls: cannot open directory '/etc/docker': Permission denied
command terminated with exit code 2
```
=> OCPBUGS-55918: set SELinux type for operator-controller

openshift/default-catalog-consistency/.gitignore, openshift/default-catalog-consistency/Makefile
See: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_operator-framework-operator-controller/366/pull-ci-openshift-operator-framework-operator-controller-main-default-catalog-consistency/1929498213128081408/artifacts/default-catalog-consistency/default-catalog-tests/artifacts/junit_olm.xml
/cherrypick release-4.19 release-4.18 release-4.17
=> OCPBUGS-56956, OPRUN-3914:  [Default Catalog Consistency Test]: fix junit output format to allow generate xml

openshift/registry.Dockerfile
Update the e2e registry Dockerfile to use golang 1.24/OCP 4.20
=> NO-ISSUE: Update e2e registry to use 1.24/4.20

internal/operator-controller/rukpak/preflights/crdupgradesafety/checks.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/checks_test.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety.go
Motivation:
When attempting to upgrade argocd-operator from v0.5.0 to v0.7.0, the upgrade process fails during the preflight CRD safety validation. The validation correctly detects that the `argocds.argoproj.io` CRD has been modified between the two versions.
The specific error reported is:
```
CustomResourceDefinition argocds.argoproj.io failed upgrade safety validation. "ChangeValidator" validation failed: version "v1alpha1", field "^.status.applicationController" has unknown change, refusing to determine that change is safe
```
However, changes between the CRD versions in this instance are limited to non-functional updates in the description fields of various properties (e.g., status.applicationController).`ChangeValidator` lacks a specific rule to classify a description-only update as …
=> [release-4.19] OCPBUGS-58284: Safely handle changes to description fields(#2023)

openshift/tests-extension/Makefile
Follow up of: #383
We missed a `check-metadata` which was added in the review, and we convey that we cannot do this check so far, and I missed the cleanup before getting merged
```
~/go/src/github/operator-framework-operator-controller/openshift/tests-extension (fix-remove-target) $ make verify
go mod tidy
go fmt ./...
go vet ./...
/Users/camilam/go/bin/golangci-lint-v2.1.6 run
0 issues.
```
NOTE: After this fix, we can enable it in the CI and avoid errors: https://github.com/openshift/release/pull/66931
=> OPRUN-3963: UPSTREAM: <carry>: [OTE] - chore: follow up #383 – fix make verify 

openshift/operator-controller/build-test-registry.sh, openshift/registry.Dockerfile
Upstream now uses a different image
=> NO-ISSUE: Remove build of test image registry

openshift/catalogd/cp-manifests, openshift/operator-controller/cp-manifests
The standard manifest was being copied rather than the experimental manifest. This meant that the expected feature-flags are not present. This is failing now that we are doing a check for those feature-flags.
=> NO-ISSUE: Fix experimental manifest copying

hack/test/pre-upgrade-setup.sh, internal/operator-controller/rukpak/convert/registryv1.go, test/e2e/cluster_extension_install_test.go, testdata/images/bundles/test-operator/v1.0.0/manifests/testoperator.clusterserviceversion.yaml, testdata/images/bundles/test-operator/v1.0.0/manifests/testoperator.networkpolicy.yaml
This is a hack to backport "NetworkPolicy object kind in bundles" support from https://github.com/operator-framework/operator-registry/pull/1675 The feature was introduced in OCP 4.20 with a operator-registry bump to v1.55.0. Ref:
1. operator-registry v1.55.0 release: https://github.com/operator-framework/operator-registry/releases/tag/v1.55.0
2. operator-registry bump in OCP 4.20: https://github.com/operator-framework/operator-controller/pull/1981 
Because the upstream PR is not being backported in operator-registry to older tags (with new z stream releases), this achieves a downstream-only backport for this feature.
We're backporting this support to prevent any breakage in case a bundle is included in a 4.19 catalog.
=> OCPBUGS-60380: Backporting NetworkPolicy support for OLM bundles

openshift/tests-extension/Makefile
Using go-bindata is causing problems with ART builds.
This removes the use of go-bindata from the builds.
This will subsequently require that users MANUALLY run the `bindata` target to refresh the bindata, or use the `build-update` target.
This is a quickfix to put out the fire.
=> NO-ISSUE: Remove bindata generation from build

openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/catalogd/manifests-experimental/18-deployment-openshift-catalogd-catalogd-controller-manager.yml, openshift/catalogd/manifests/18-deployment-openshift-catalogd-catalogd-controller-manager.yml, openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml, openshift/operator-controller/manifests-experimental/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml, openshift/operator-controller/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml
There is a problem when the service-ca certificate is not available at pod start. This is an issue because the SystemCertPool is created from SSL_CERT_DIR, which may include the empty service-ca. The SystemCertPool is never regenerated during the lifetime of the program execution, so it will never get updated when the service-ca is filled. Thus, we need to use --pull-cas-dir to reference the CAs that we want to use. This will also allow OLMv1 to reload the service-ca when it is reloaded (after 2 years, mind you). Removing the SSL_CERT_DIR setting, and adding the --pull-cas-dir flag ought to be equivalent to what we have now (i.e. SSL_CERT_DIR and no --pull-cas-dir), except that rotation will be handled better.
=> NO-ISSUE: Handle service-ca cert availability/rotation

openshift/tests-extension/.openshift-tests-extension/openshift_payload_olmv1.json, openshift/tests-extension/pkg/helpers/catalogs.go, openshift/tests-extension/pkg/helpers/commands.go, openshift/tests-extension/pkg/helpers/dump.go, openshift/tests-extension/test/olmv1-incompatible.go, openshift/tests-extension/test/webhooks.go
It reintroduces the reverted PR [#434](https://github.com/openshift/operator-framework-operator-controller/pull/434),  
but **without** the failing test (as agreed in [Slack thread](https://redhat-internal.slack.com/archives/C06KP34REFJ/p1755277096753809?thread_ts=1755273190.823239&cid=C06KP34REFJ)).  
The base reference for this file is [#442](https://github.com/openshift/operator-framework-operator-controller/pull/442), which was reverted [#434].  
---
**Removed test**  
:x: `It("should be tolerant to openshift-service-ca certificate rotation", …)`  
‣ Failed → reason for the revert  
**Added** (requested in [#424 review](https://github.com/openshift/operator-framework-operator-controller/pull/424)  
:white_check_mark: *Diagnostics & dumps*  
- `AfterEach` failure hook → pod logs, …
=> OPRUN-3941: [OTE] Add webhook tests (without should be tolerant to openshift-service-ca certificate rotation)

openshift/tests-extension/.openshift-tests-extension/openshift_payload_olmv1.json, openshift/tests-extension/test/webhooks.go
This PR introduces the test that we faced intermitent issues in the OCP test env.
You can compare the migration from original: https://github.com/openshift/origin/pull/30059/files#diff-6dd6fa78ac85235012d3c9910f8510bc1640c830a83888681bd5922cec0dffcbR149-R164
**What fixed the test:**
- We wait for the webhook service cert secret to be recreated and populated before checking responsiveness.
- We use longer timeouts, since the short ones were too tight for these envs
**Tests**
(agreggate 10 times)
See details on https://pr-payload-tests.ci.openshift.org/runs/ci/52b277e0-7df6-11f0-99c5-0f4a557cd6de-0
```
Will run 1 of 1 specs
------------------------------
[sig-olmv1][OCPFeatureGate:NewOLMWebhookProviderOpenshiftServiceCA][Skipped:Disconnected][Serial] OLMv1 operator with webhooks should be …
```
=> OCPBUGS-60564: [OTE] Add webhook to validate openshift-service-ca certificate rotation

openshift/tests-extension/.openshift-tests-extension/openshift_payload_olmv1.json, openshift/tests-extension/pkg/helpers/cluster_catalog.go, openshift/tests-extension/test/olmv1-catalog.go
This commit migrates the olmv1_catalog set of tests from openshift/origin
to OTE as part the broad effort to migrate all tests.
We are also doing some improvements to avoid flakes by ensuring cleanup and unique names
See that pass in the aggregation as well: https://pr-payload-tests.ci.openshift.org/runs/ci/48ad6920-7da7-11f0-93ef-7fa1591d2e23-0
=> OPRUN-4054: [OTE] add catalog tests from openshift/origin

openshift/tests-extension/test/olmv1-catalog.go
Because we were using the same hardcoded catalog name, when multiple tests ran at the same time, there was a resource collision. This ensures the catalog name will be unique for each test run so we don't need to worry about collisions.
=> OCPBUGS-60945: UPSTREAM: <carry>: Ensure unique name for bad-catalog tests

openshift/tests-extension/OWNERS
The current owners are defined in [OWNERS_ALIASES](https://github.com/openshift/operator-framework-operator-controller/blob/main/OWNERS_ALIASES). However, with the OTE process, more and more QE test cases will be contributed to this folder. It would be better if QE also had approval permissions.
Hi @oceanc80 and @joelanford , could you help approve it when you get a chance? Thanks!
=> NO-ISSUE: Grant QE approver permissions for OTE contributions

internal/operator-controller/controllers/clusterextension_controller.go, internal/operator-controller/controllers/common_controller.go, internal/operator-controller/controllers/common_controller_test.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/crdupgradesafety_test.go, internal/operator-controller/rukpak/preflights/crdupgradesafety/unhandled_message_test.go, testdata/manifests/crd-unhandled-new.json, testdata/manifests/crd-unhandled-old.json
**ClusterExtension upgrade could fail due to oversized CRD validation status updates**
When upgrading a ClusterExtension, CRD validation status updates could exceed the Kubernetes 32 KB limit, causing the update to fail with the error “Too long: may not be more than 32768 bytes.” This prevented the ClusterExtension status from being updated, leaving no status conditions or information about why the upgrade did not occur.
This issue occurred when the crddiff library returned a large JSON diff for unhandled CRD changes.
The problem has been resolved by truncating and summarising the diff output for unhandled scenarios, instead of including the full JSON diff. This ensures status updates remain within size limits and users receive clear, actionable error messages.
- Cherry-pick of: …
=> OCPBUGS-62722: (cherry-pick) Fix truncate large error messages and unhandle changes for crd upgrade safety in status conditions 

openshift/tests-extension/pkg/helpers/cluster_extension.go, openshift/tests-extension/test/olmv1-incompatible.go
Cheery-pick of https://github.com/openshift/operator-framework-operator-controller/pull/501
=> OCPBUGS-62811: for incompatible test add func to wait builder and deployer SA creation by OCP controller
