openshift/operator-framework-operator-controller

openshift/operator-controller.Dockerfile

UPSTREAM: <carry>: local Dockerfile

---

DOWNSTREAM_OWNERS
DOWNSTREAM_OWNERS_ALIASES

UPSTREAM: <carry>: config downstream owners

---

openshift/operator-controller.Dockerfile

UPSTREAM: <carry>: align dockerfile and manifests for bin target

---

openshift/generate-manifests.sh

UPSTREAM: <carry>: conditionally rename manifests

---

.github/workflows/unit-test.yaml
internal/resolution/variable_sources/bundlesanddependencies/bundles_and_dependencies_test.go
internal/resolution/variable_sources/crdconstraints/crd_constraints_test.go

Update to upstream main commit 98b6a9e

---

openshift/operator-controller.Dockerfile

UPSTREAM: <carry>: add USER to openshift dockerfile

---

openshift/generate-manifests.sh
openshift/manifests/11-deployment-openshift-operator-controller-operator-controller-controller-manager.yml

UPSTREAM: <carry>: add scheduling preference/priorityClass annotations

---

config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
openshift/manifests/11-deployment-openshift-operator-controller-operator-controller-controller-manager.yml

UPSTREAM: 290: Remove Resource Limits (#290)

---

openshift/operator-controller.Dockerfile

UPSTREAM: <carry>: add manifests to image

---

openshift/Makefile
openshift/commitchecker/README.md
openshift/commitchecker/commitchecker.go
openshift/commitchecker/git.go
openshift/commitchecker/git_test.go
openshift/commitchecker/validate.go
openshift/commitchecker/validate_test.go

Add commitchecker

---

.ci-operator.yaml
openshift/operator-controller.Dockerfile

OCPBUGS-19096: UPSTREAM: <carry>: Updating ose-olm-operator-controller images to be consistent with ART

---

go.mod
go.sum
vendor/modules.txt

Add the go mod rewrite, now that catalogd has been merged.

NO-ISSUE: UPSTREAM: <drop>: rewrite go mod

---

DOWNSTREAM_OWNERS
DOWNSTREAM_OWNERS_ALIASES

Also `s/runtime/framework/g` in the DOWNSTREAM_OWNERS

NO-ISSUE: UPSTREAM: <carry>: Add tmshort to approvers

---

openshift/generate-manifests.sh
openshift/kustomize/overlays/openshift/kustomization.yaml

This fixes the calling of kustomize similar to https://github.com/openshift/operator-framework-catalogd/pull/63

NO-ISSUE: UPSTREAM: <carry>: Properly copy and call kustomize

---

openshift/generate-manifests.sh
openshift/kustomize/overlays/openshift/kustomization.yaml
openshift/kustomize/overlays/openshift/patches/manager_deployment_mount_auth_host.yaml
openshift/manifests/18-deployment-openshift-operator-controller-operator-controller-controller-manager.yml

This reverts commit ddffae9c8fcb653025610201ae95717b5f137676.

NO-ISSUE: UPSTREAM: <carry>: Revert "UPSTREAM: <carry>: Add hostPath mount for `/var/lib/kubelet`"

---

catalogd/internal/serverutil/serverutil.go
go.mod
internal/resolve/catalog.go
vendor/github.com/gorilla/handlers/.editorconfig
vendor/github.com/gorilla/handlers/.gitignore
vendor/github.com/gorilla/handlers/LICENSE
vendor/github.com/gorilla/handlers/Makefile
vendor/github.com/gorilla/handlers/README.md
vendor/github.com/gorilla/handlers/canonical.go
vendor/github.com/gorilla/handlers/compress.go
vendor/github.com/gorilla/handlers/cors.go
vendor/github.com/gorilla/handlers/doc.go
vendor/github.com/gorilla/handlers/handlers.go
vendor/github.com/gorilla/handlers/logging.go
vendor/github.com/gorilla/handlers/proxy_headers.go
vendor/github.com/gorilla/handlers/recovery.go
vendor/modules.txt

Upstream PR #1564; this is expected to be replaced on the next upstream sync
(cherry picked from commit a19f91ae4003f0f961f35361d585b2abe5e82614)

OCPBUGS-46516: improve logging: catalog http server, op-con resolver

---

internal/resolve/catalog.go

Based on upstream PR #1564
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
(cherry picked from commit a19f91ae4003f0f961f35361d585b2abe5e82614)
Signed-off-by: Todd Short <todd.short@me.com>
(cherry picked from commit e6da52db39ac48c803870d8d95473c51260ec0c9)

OCPBUGS-48813: improve logging: catalog http server, op-con resolver [release-4.18]

---

openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml

Signed-off-by: Todd Short <todd.short@me.com>
(cherry picked from commit 637b45c725fb89a58c8c5d0ef123a41a96e25d16)

OCPBUGS-49439: Resolve issue with pre-mature mounting of service CA configmap

---

openshift/catalogd/generate-manifests.sh
openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
openshift/catalogd/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_annotations.yaml
openshift/catalogd/manifests/00-namespace-openshift-catalogd.yml
openshift/operator-controller/generate-manifests.sh
openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
openshift/operator-controller/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_annotations.yaml
openshift/operator-controller/manifests/00-namespace-openshift-operator-controller.yml

Add openshift node selector annotation

OCPBUGS-54179: Add openshift node selector annotation

---

openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
openshift/manifests/20-deployment-openshift-operator-controller-operator-controller-controller-manager.yml

Manual cherry-pick of ad558820f8aeab24ddb98321901cd03d280b9346

OCPBUGS-55172: Add catalogd-cas-dir option to op-con [release-4.18]

---

openshift/default-catalog-consistency/hack/policy.json

The directory is not used and should not be merged.
So, I am cleaning it up.

NO-ISSUE: [Default Catalog](cleanup) Remove hack directory which is not used

---

openshift/default-catalog-consistency/pkg/check/all.go

Those are fixed now by pipeline: https://issues.redhat.com/browse/ISV-5920?focusedId=27307508&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27307508

OPRUN-3951: [Default Catalog Consistency Test]: Enable CatalogChecks

---

openshift/tests-extension/README.md

NO-ISSUE:  Readme:Add info to help use payload-aggregate with new tests
